# This file controls what config variables you want to be able to allow your users
# to set, as well as those you'll be able to access from within the application.
# 
# If you want to be able to access a string config[:site_title], for example:
#   
films_per_page:
  name: Site Title
  type: integer
  default: 28

postings_per_page:
  name: Site Title
  type: integer
  default: 2

posting_redy:
  name: Site Title
  type: integer
  default: 5
  
comments_per_page:
  name: Site Title
  type: integer
  default: 5

info_blog:
  name: Site Title
  type: integer
  default: 3

blog_redy:
  name: Site Title
  type: integer
  default: 3

password:
  name: Pasw
  type: integer
  default: 2


registration_from:
  name: email_site
  type: string
  default: oleg@example.com 


delay_comment_notifications:
  name: Site Title
  type: integer
  default: 8 

info_blog_per_page:
  name: Site Title
  type: integer
  default: 2
  
blogs_per_page:
  name: Site Title
  type: integer
  default: 3

copyright:
  name: Site Title
  type: string
  default: oleg prin

name: 
  name: Site Title
  type: string
  default: oleg internet shop

slogan: 
  name: Site Title
  type: string
  default: magazin

admin_notification_address:
  name: Site Title
  type: string
  default: oleg.example@gmail.com
# 'name' is the name that appears in the edit form
# 
# 'type' can be 'string' for a text field, 'password' for a password field or 'text' for a text area
#   'type' defaults to 'string'
# 
# 'default' is the default value to use if there's no entry in the database. Otherwise, nil will be returned
# 
# Some Examples:
#   
# site_title:
#   name: Site Title
#   default: My Site
#   type: string
#   
# site_description:
#   name: Description for Google
#   default: Lots of Awesomeness Here
#   type: text
#   
# secret:
#   name: Secret Password for Accessing Secret Areas
#   default: secret
#   type: password